from .app import create_app
from .cli import main
from .config import (
    BASE_DIR,
    DATABASE_URL,
    INDEX_FILE,
    PUBLIC_ORIGIN,
    STATIC_DIR,
    WEB_DIR,
    database_url,
    public_origin,
    redacted_database_url,
)
from .handlers import (
    create_group,
    create_url,
    delete_url_by_id,
    edit_group,
    edit_url,
    export_data,
    get_url_icon,
    import_data,
    list_groups,
    list_urls,
    move_url_group,
    refresh_url_metadata,
    refresh_url_title,
    reorder_groups,
    set_important,
)
from .handlers import (
    delete_group as delete_group_handler,
)
from .page_titles import fetch_url_title, parse_title
from .storage import (
    add_group,
    add_url,
    alembic_config,
    delete_group,
    dispose_engine,
    export_saved_data,
    find_group_record,
    flatten_group_records,
    get_connection,
    get_engine,
    import_saved_data,
    move_url_to_group,
    read_group_record_by_name,
    read_group_records,
    read_url_group_ids,
    read_url_record,
    read_url_record_by_id,
    read_url_records,
    read_urls,
    remove_url_by_id,
    run_migrations,
    set_url_important,
    update_group,
    update_group_order,
    update_url_created_at,
    update_url_record,
    update_url_title,
    verify_db_at_head,
)
from .storage import (
    create_group as create_group_record,
)
from .url_normalization import normalize_url

__all__ = [
    "BASE_DIR",
    "DATABASE_URL",
    "INDEX_FILE",
    "PUBLIC_ORIGIN",
    "STATIC_DIR",
    "WEB_DIR",
    "add_group",
    "add_url",
    "alembic_config",
    "create_app",
    "create_group",
    "create_group_record",
    "create_url",
    "database_url",
    "delete_url_by_id",
    "delete_group",
    "delete_group_handler",
    "dispose_engine",
    "edit_group",
    "edit_url",
    "export_data",
    "export_saved_data",
    "fetch_url_title",
    "find_group_record",
    "flatten_group_records",
    "get_connection",
    "get_engine",
    "get_url_icon",
    "import_data",
    "import_saved_data",
    "list_groups",
    "list_urls",
    "main",
    "move_url_group",
    "move_url_to_group",
    "normalize_url",
    "parse_title",
    "public_origin",
    "read_group_records",
    "read_group_record_by_name",
    "read_url_record",
    "read_url_record_by_id",
    "read_url_group_ids",
    "read_url_records",
    "read_urls",
    "redacted_database_url",
    "reorder_groups",
    "refresh_url_metadata",
    "refresh_url_title",
    "remove_url_by_id",
    "run_migrations",
    "set_important",
    "set_url_important",
    "update_url_created_at",
    "update_group_order",
    "update_group",
    "update_url_record",
    "update_url_title",
    "verify_db_at_head",
]
